### PR TITLE
Uniform mesh check modification

### PR DESCRIPTION
**Pull request by keckler**
This is in relation to #471 .

### CODE REVIEW

**Review by john-science — APPROVED** [review]

**Comment by john-science** [comment]
I really appreciate the fix!

And the fast turn-around.

What I would like to push for, in the future, is if we are fixing a bug we add a new unit test to prove the bug is fixed.

While that may not always be easy to do, if it is, it will help us in lots of ways. In particular, the unit test will call out a feature that we think is important to work in a certain way, but has been tricky to do right in the past.

@keckler   Do you think it would be doable to unit test this issue?

**Comment by keckler** [comment]
I did give some thought to a unit test for this PR. My conclusion was that a small unit test would be a little bit difficult for this particular piece of code, because it requires a lot of scaffolding just to have the required inputs. Since I am not really versed in how ARMI even gets to this point, I didn't make a test for it at this time. 

I am going to upload an example case to the original issue sometime today, and we can probably make an integration test from that.

**Comment by jakehader** [comment]
@john-science, this is a tricky unit test because it requires some reactor model to be initialized with detailed axial expansion enabled, with power assigned to the blocks. This was uncovered through our benchmark work, so an in-use test might be more appropriate.

What are your thoughts? A test could probably we whipped up but it might be a lot of initialization code.

**Comment by keckler** [comment]
Check [this comment on the original issue](https://github.com/terrapower/armi/issues/471#issuecomment-966557299) for an example case that causes the code to fail before the current PR is merged in.

Note that I am using an internal TerraPower application to run the neutronics calcs with ARMI. It may not fail when running just the framework, but the issue stems from the framework.

**Comment by john-science** [comment]
@keckler That's a bit of a shame. It would be nice if there was an easy way to test this. But I can't think of a similar test to copy from off the top of my head.

Well, going forward we will try to find ways to test things we fix.  It's a good goal to have. Thanks!

**Pull request merged**
