### PR TITLE
Harmonize material names and class names

### PR DESCRIPTION
**Pull request by alexhjames**
## Description

For `materials.resolveMaterialClassByName()` to function, `material.name` and the class name should be the same. This PR ensures that is true for all materials. 

No testing was added as the name field on the material isn't really something to be tested. 

---

## Checklist

- [x] This PR has only one purpose or idea.
- [x] Tests have been added/updated to verify that the new/changed code works.

- [x] The code style follows [good practices](https://terrapower.github.io/armi/developer/standards_and_practices.html).
- [x] The commit message(s) follow [good practices](https://terrapower.github.io/armi/developer/tooling.html).

- [x] The [release notes](https://terrapower.github.io/armi/release/index.html) (location `doc/release/0.X.rst`) are up-to-date with any bug fixes or new features.
- [x] The documentation is still up-to-date in the `doc` folder.
- [x] The dependencies are still up-to-date in `setup.py`.

### CODE REVIEW

**Comment by keckler** [comment]
If we're gonna do this, I welcome you to fix all the broken blueprints files in our benchmark models :-)

**Review by john-science — APPROVED** [review]
Approved, pending testing.

**Comment by alexhjames** [comment]
> If we're gonna do this, I welcome you to fix all the broken blueprints files in our benchmark models :-)

I don't think this needed. We ran into this in terrapower-twr a few months ago with T92Depleted vs T92-Depleted-Boron. The blueprints use the class name not the name field.

**Comment by keckler** [comment]
Well I'll be darned, you're right. Forget my snarky comment!

**Comment by john-science** [comment]
Two unit tests failing:

```
Traceback (most recent call last):
  File "/home/runner/work/armi/armi/armi/tests/test_lwrInputs.py", line 67, in test_loadC5G7
    self.assertIn("Uranium Oxide", streamVal, msg=streamVal)
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/unittest/case.py", line 1179, in assertIn
    self.fail(self._formatMessage(msg, standardMsg))
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/unittest/case.py", line 753, in fail
    raise self.failureException(msg)
AssertionError: 'Uranium Oxide' not found in '[warn] Ignoring invalid settings: fakeBad\n=========== Settings Validation Checks ===========\n[warn] Burn chain already imposed. Skipping 
```

**Comment by alexhjames** [comment]
@john-science  Two unit tests are updated! Sorry I didn't catch those locally

**Comment by sombrereau** [comment]
@alexhjames / @john-science  This broke a few of my internal unittests because of name changes to Uranium Oxide and Zirconium. No big deal, but I think we need to do a better job communicating these kinds of changes ... or maybe on my end listening for these kinds of changes.

**Pull request merged**
