### PR TITLE
Removing unused class ConfigHandler

### PR DESCRIPTION
**Pull request by theJollySin**
The `ConfigHandler` class is entirely unused in this repo.  I am told it should be moved to the GUI plugin repo/project, as that is where it is used.

### CODE REVIEW

**Comment by theJollySin** [comment]
I did a little grepping around and found a few other unused classes as well.  Some of them look like they might provide functionality for users of the framework, so I didn't want to just delete them all without asking the experts.  (None of these are used in unit tests either.)

I found 17 other unused classes in the repo:

| File        | Class           | 
| :------------- |:-------------:| 
| armi/bookkeeping/historyTracker.py | HistoryProcessor |
| armi/cases/inputModifiers/neutronicsModifiers.py | NeutronicMeshsSizeModifier |
| armi/cases/suiteBuilder.py | FullFactorialSuiteBuilderNoisy |
| armi/physics/fuelPerformance/executers.py | FuelPerformanceExecuter |
| armi/physics/fuelPerformance/executers.py | FuelPerformanceOptions |
| armi/physics/neutronics/isotopicDepletion/isotopicDepletionInterface.py | AbstractIsotopicDepleter |
| armi/physics/neutronics/isotopicDepletion/isotopicDepletionInterface.py | AbstractIsotopicDepletionReader |
| armi/physics/neutronics/isotopicDepletion/isotopicDepletionInterface.py | Csrc |
| armi/physics/neutronics/latticePhysics/latticePhysicsInterface.py | LatticePhysicsInterface |
| armi/physics/neutronics/macroXSGenerationInterface.py | MacroXSGenerationInterface |  
| armi/reactor/components/__init__.py | PositiveOrNegativeVolumeComponent |
| armi/reactor/components/__init__.py | ZeroMassComponent |
| armi/reactor/converters/geometryConverters.py | BlockNumberModifier |
| armi/reactor/converters/meshConverters.py | AxialExpansionModifier |
| armi/reactor/converters/parameterSweeps/generalParameterSweepConverters.py | CustomModifier |
| armi/runLog.py | PrintLogCombined |
| armi/scripts/migration/base.py | GeomMigration |

Perhaps easier to remove safely, I found the following 11 unused Exception classes:

| File        | Class           | 
| :------------- |:-------------:| 
| armi/localization/exceptions.py | DeprecationError |
| armi/localization/exceptions.py | InputInspectionRequired |
| armi/localization/exceptions.py | InvalidSettingsFileContentsError |
| armi/localization/exceptions.py | NoDataModelInDatabaseException |
| armi/localization/exceptions.py | NonexistentSettingsFileError |
| armi/localization/exceptions.py | RMFluxPartisnError |
| armi/localization/exceptions.py | RZMFlxPartisnError |
| armi/localization/exceptions.py | ReactivityCoefficientNonExistentComponentsInRepresentativeBlock |
| armi/localization/exceptions.py | SettingNameCollision |
| armi/localization/exceptions.py | XSGenerationError |
| armi/mpiActions.py | MpiActionError |

**Review by youngmit — APPROVED** [review]
Yet another good cleanup. Making note of this commit so that I can shuffle this over to our GUI plugin

**Comment by youngmit** [comment]
Regarding other unused classes, some of them do see some use in applications, but may not be as well tested as they should be. This includes the exception classes. The history there is that there was a time when we were expecting ARMI to see some use overseas, so we made a partial attempt at internationalization, but kind of did it wrong; rather than using `gettext` or `i18n`, we made all of these exception classes. We never actually translated anything, so the easiest thing to do is probably to burn them all down and replace with whatever the nearest standard Exception base class is. In the future if we want to make an earnest attempt at translating ARMI, there are better tools. Subclassing Exception to do internationalization is kind of an abuse of the Python exception system anyways. We will have to do some (admittedly simple) groundwork internally before we can just nuke them all though.

**Comment by theJollySin** [comment]
@youngmit  I mean, they are just a bunch of little commits, I get that.  It just feels like the right time for me to do them, as I am learning my way around the code base.

And I can take a look at the exceptions.

**Comment by youngmit** [comment]
In a perfect world, the localization package would be entirely gone. We just _are_ currently using all of those exceptions in various plugins. If you wanted to work on a PR that wipes the whole package out, rejiggering the ARMI-internal uses of the `localization.exceptions` to standard exceptions with whatever messages the old class was using, I can tackle the ones that we have on our side and we can meet in the middle?

**Comment by theJollySin** [comment]
> If you wanted to work on a PR that wipes the whole package out, rejiggering the ARMI-internal uses of the `localization.exceptions` to standard exceptions with whatever messages the old class was using, I can tackle the ones that we have on our side and we can meet in the middle?

Yeah, I can do this.  It'll be a simple PR to build.  Though it will touch a lot of files again, of course.

**Pull request merged**
