### PR TITLE
Sorting imports with ruff

### LINKED ISSUE #2021: Sort imports using ruff
I have tried the [ruff import tools](https://docs.astral.sh/ruff/rules/#isort-i), and I think they are going to work for us.

I tried it on a bunch of files, and it seems like it would work.

This solution was suggested by @drewj-tp , but I figure it would also have saved @mgjarrett some time in the past, too.

### PR DESCRIPTION
**Pull request by john-science**
## What is the change?

Sorting the imports with `ruff`.

## Why is the change being made?

A few times in the last month, I have had to bother people in their PRs about alphabetizing imports.  Well, that's boring and a waste of time.

I think `ruff` does a good job with making all our imports consistent, but not breaking the paradigms we have. So, this seems better.

close #2021

---

## Checklist

- [x] This PR has only [one purpose or idea](https://terrapower.github.io/armi/developer/tooling.html#one-idea-one-pr).
- [x] [Tests](https://terrapower.github.io/armi/developer/tooling.html#test-it) have been added/updated to verify any new/changed code.

- [x] The code style follows [good practices](https://terrapower.github.io/armi/developer/standards_and_practices.html).
- [x] The commit message(s) follow [good practices](https://terrapower.github.io/armi/developer/tooling.html).

- [x] The [release notes](https://terrapower.github.io/armi/developer/tooling.html#add-release-notes) have been updated if necessary.
- [x] The [documentation](https://terrapower.github.io/armi/developer/tooling.html#document-it) is still up-to-date in the `doc` folder.
- [x] The dependencies are still up-to-date in `pyproject.toml`.

### CODE REVIEW

**Comment by opotowsky** [comment]
What is the addition of the I001 ignores doing?

**Comment by john-science** [comment]
> What is the addition of the I001 ignores doing?

As it turns out, if you alphabetize the imports in those two files, then we get circular import errors.

Fun!

That's worth me looking at and fixing. But this PR is already big enough, I didn't want to mingle the two ideas and make it harder on you.

**Comment by john-science** [comment]
Again, I apologize for myself.

What a thing to review.

Please consider there is no timeline for this. 

And scream if I need to break this into smaller PRs or something. I can do that!

**Comment by opotowsky** [comment]
Haha no worries! maybe next week! or while I'm flying

**Review by opotowsky — APPROVED** [review]
We did it!

**Pull request merged**
