### PR TITLE
Fix getNeighboringCellIndices

### PR DESCRIPTION
**Pull request by mgjarrett**
## What is the change?

The staticmethod to get neighboring cell indices in a `StructuredGrid` is implemented incorrectly:

https://github.com/terrapower/armi/blob/14c951a05214154a1e6bfb43c728aa714084cea7/armi/reactor/grids/structuredgrid.py#L379-L382

It looks like a typo; there is a `1` where there should be an `i`.

Also, a unit test is added to cover this function.

## Why is the change being made?

The previous implementation is incorrect.

---

## Checklist

- [x] This PR has only [one purpose or idea](https://terrapower.github.io/armi/developer/tooling.html#one-idea-one-pr).
- [x] [Tests](https://terrapower.github.io/armi/developer/tooling.html#test-it) have been added/updated to verify that the new/changed code works.

- [x] The code style follows [good practices](https://terrapower.github.io/armi/developer/standards_and_practices.html).
- [x] The commit message(s) follow [good practices](https://terrapower.github.io/armi/developer/tooling.html).

- [x] The [release notes](https://terrapower.github.io/armi/release/index.html) (location `doc/release/0.X.rst`) are up-to-date with any important changes.
- [x] The [documentation](https://terrapower.github.io/armi/developer/tooling.html#document-it) is still up-to-date in the `doc` folder.
- [x] If any [requirements](https://terrapower.github.io/armi/developer/tooling.html#watch-for-requirements) were affected, mention it in the [release notes](https://terrapower.github.io/armi/release/index.html).
- [x] The dependencies are still up-to-date in `pyproject.toml`.

### CODE REVIEW

**Review by john-science — APPROVED** [review]

**Comment by opotowsky** [comment]
Whoah nice catch! Will this affect internal integration testing?

**Comment by john-science** [comment]
> Whoah nice catch! Will this affect internal integration testing?

Michael did that testing. This is ready for prime time.

**Comment by drewj-usnctech** [comment]
FWIW this existed prior to the refactoring in #1373 

https://github.com/terrapower/armi/blob/da28372a240e80418139d1069317f546af9bcd8d/armi/reactor/grids.py#L929-L932

My intention there was just to copy code off `Grid` and move it to `StructuredGrid`. But I'm glad it has been discovered and fixed!

**Comment by mgjarrett** [comment]
Ah, I didn't look that closely. Didn't see the side-by-side diff because it was moved to a new file.

It looks like this had been around for over 5 years (probably much longer). I guess this shows how little exercise the Cartesian code gets.

image

**Pull request merged**
