### PR TITLE
Fix typo in `suiteBuilder` API

### PR DESCRIPTION
**Pull request by keckler**
## Description

Just a small typo that I came across in the API.

---

## Checklist

- [x] This PR has only one purpose or idea.
- [ ] Tests have been added/updated to verify that the new/changed code works.

- [x] The code style follows [good practices](https://terrapower.github.io/armi/developer/standards_and_practices.html).
- [x] The commit message(s) follow [good practices](https://terrapower.github.io/armi/developer/tooling.html).

- [ ] The [release notes](https://terrapower.github.io/armi/release/index.html) (location `doc/release/0.X.rst`) are up-to-date with any bug fixes or new features.
- [x] The documentation is still up-to-date in the `doc` folder.
- [x] The dependencies are still up-to-date in `setup.py`.

### CODE REVIEW

**Review by jakehader — APPROVED** [review]

**Comment by john-science** [comment]
@keckler Note the phrasing of that checklist bullet: "the release notes are up-to-date with any bug fixes or new features."

I phrased them that way instead of "please add something to the release notes", so that everyone could check all the boxes in the check list.  If you can't check this box, let's find a phrasing that you Would check in a PR.  

Just thinking aloud.

**Comment by john-science** [comment]
Technically, this is a backwards compatibility-breaking API change.

But I can't find this method used anywhere downstream. So I'll just merge the PR.

Though it does make me wonder... could we just delete this method and nothing downstream would break?

**Comment by keckler** [comment]
I do typically check that box! I just didn't do it this time because I figured it was such a tiny change, I didn't even make a branch on my own computer, I just did it straight on GH. 

And like you said, nobody uses that method.

Just figured it wasn't worth it. My bad.

**Comment by keckler** [comment]
Meanwhile, @mgjarrett checks the box in #1002 without even actually making any changes to the release notes! 🤣

**Comment by mgjarrett** [comment]
> Meanwhile, @mgjarrett checks the box in #1002 without even actually making any changes to the release notes! 🤣

I was just following the last 8 PRs that removed parameters but didn't update the release notes. I assumed that means moving parameters isn't worthy of a release note.

**Comment by keckler** [comment]
Hmm, okay, perhaps I am misinterpreting that checkbox. 

I didn't check it because I didn't change the release notes. But I guess the box doesn't say "check this if you made any change at all and put it in the release notes".

There is the possibility that if change is not a "bug fix" or a "new feature", then the release notes are still up to date, and so I should check it. Alright, I can see that. 

Will check in the future for all things that are not "bug fixes" or "new features"!

**Pull request merged**
