### PR TITLE
Fixing copper density curve

### PR DESCRIPTION
**Pull request by john-science**
## Description

The copper density provided in the reference is, of course, for 3D density. So this is a Minor bug fix for a material that I think is broadly unused in the ARMI ecosystem. I expect this to make no difference to our major downstream projects.

---

## Checklist

- [X] This PR has only one purpose or idea.
- [X] Tests have been added/updated to verify that the new/changed code works.

- [X] The code style follows [good practices](https://terrapower.github.io/armi/developer/standards_and_practices.html).
- [X] The commit message(s) follow [good practices](https://terrapower.github.io/armi/developer/tooling.html).

- [X] The [release notes](https://terrapower.github.io/armi/release/index.html) (location `doc/release/0.X.rst`) are up-to-date with any bug fixes or new features.
- [X] The documentation is still up-to-date in the `doc` folder.
- [X] The dependencies are still up-to-date in `setup.py`.

### CODE REVIEW

**Comment by john-science** [comment]
Uh oh. 

We are getting the same bizarro-world errors that Chris recently got in an unrelated PR: https://github.com/terrapower/armi/issues/1144

Something is wrong with, perhaps, the Materials tests base class.

Drat.

**Review by opotowsky — APPROVED** [review]
🎉

**Comment by opotowsky** [comment]
> 🎉

Oops I didn't see the message about the CI failure yet. Peeking into that

**Comment by john-science** [comment]
Okay, if I remove the new tests, but leave the Copper change, the tests pass.

So, that's information.

**Comment by john-science** [comment]
So, after extensive A/B testing and git bisecting, I determined that removing these two tests from the `_Material_Test` baseclass solves the problem:

https://github.com/terrapower/armi/blob/5cfddf607691184eb407c5ea8a55c9f31396d8fd/armi/materials/tests/test_materials.py#L52-L56

Unfortunately, I have no solid explanation as to why. yet.

**Comment by opotowsky** [comment]
Oh goodness. I would congratulate you but this has to be so frustrating!

**Pull request merged**
