### PR TITLE
Cleaning out unused code and adding coverage

### PR DESCRIPTION
**Pull request by john-science**
## What is the change?

This is just a general cleanup PR.

1. Removed `prepSearch()`, which was fully deprecated years ago, and verified that it wasn't used anywhere downstream.
2. Removed a strange staticmethod `SkippingXsGen_BuChangedLessThanTolerance`, which was fundamentally unused.
3. Fixed the `interactBOL` test in DB interface to stop leaving test crumbs (FINALLY, this took a long time to find).
4. Moved two functions that were inside the `FuelHandler.getAssembly()` out of that function, to make them testable.
5. Added a ton some generic code coverage.

## Why is the change being made?

I just ran afoul of the deprecated function, and wanted to do some cleanup.

---

## Checklist

- [x] This PR has only [one purpose or idea](https://terrapower.github.io/armi/developer/tooling.html#one-idea-one-pr).
- [x] [Tests](https://terrapower.github.io/armi/developer/tooling.html#test-it) have been added/updated to verify any new/changed code.

- [x] The code style follows [good practices](https://terrapower.github.io/armi/developer/standards_and_practices.html).
- [x] The commit message(s) follow [good practices](https://terrapower.github.io/armi/developer/tooling.html).

- [x] The [release notes](https://terrapower.github.io/armi/developer/tooling.html#add-release-notes) have been updated if necessary.
- [x] The [documentation](https://terrapower.github.io/armi/developer/tooling.html#document-it) is still up-to-date in the `doc` folder.
- [x] The dependencies are still up-to-date in `pyproject.toml`.

### CODE REVIEW

**Comment by albeanth** [comment]
If I could make 1 request, I know you grepped around, but please run this on the testing suite for an internal TP App before merging. Thank you, @john-science !

**Review by opotowsky — APPROVED** [review]
Nice work!!

**Comment by john-science** [comment]
> If I could make 1 request, I know you grepped around, but please run this on the testing suite for an internal TP App before merging. Thank you, @john-science !

I will do that, sure!

**Comment by john-science** [comment]
@opotowsky @albeanth Okay, I tested this downstream with the usual battery of cross-platform testing. It looks good!

**Pull request merged**
