### PR TITLE
Warning user when a Material Modification is unused.

### LINKED ISSUE #402: No warning when material modification is unused
Right now if you define an assembly with a material modification that is not recognized, ARMI does not tell you that it isn't recognized or that it is unused. For instance, I can define an assembly:

```yaml
assemblies:
  Testing123456:
    specifier: IC
    blocks:
    - name: DriverFuelBlock
      flags: FUEL
      fuel:
        shape: Circle
        material: UZr
        Tinput: 25.0
        Thot: 1500.0
        id: 0.0
        od: 0.5
        mult: 217
    height:
    - 666.0
    axial mesh points:
    - 666
    xs types:
    - B
    material modifications:
      this_is_a_fake_setting: # <--------------------------
        - 0.5
   ```

No mention of the modification `this_is_a_fake_setting` is made in the output. It would be useful for the user to know that their modifications are not recognized, at the very least as an input verification mechanism.

### PR DESCRIPTION
**Pull request by john-science**
When the user puts a material modification in a YAML file (or in code), they expect the mods to be used. In the past, a fictitious (or unused) mat mod would be passed silently. It seems greatly preferable that users be informed that their run probably wasn't what they expected.

This PR will close #402

### CODE REVIEW

**Review by ntouran — APPROVED** [review]
sorry for the delay..

**Comment by john-science** [comment]
@youngmit  I don't know. I really like the idea of adding the "did we use this material modification" check in the assembly blueprints:

https://github.com/terrapower/armi/blob/master/armi/reactor/blueprints/assemblyBlueprint.py#L97-L112

But I'm not sure if I see how that's possible. Each material would need to actually register a list of 'mat mods' they use for that to work. And they currently don't.  Maybe they should?

Or am I missing something?  Right now we just pass the material modifications to the `applyInputParams()` method on a material, and it will use it or not at it's leisure.  Is there currently some way to tell what mat mods are used that I'm not seeing?

Cheers!

**Comment by ntouran** [comment]
You're not missing anything. The materials don't communicate with one another and just apply mods as they fly by if they see one they know about. The easiest thing I think we could do (but still not trivial) would be to somehow communicate up when a modification is used. You could imagine modifications being objects that have a `.used` boolean that gets flipped from False to True, and then a thing at the end checking for any `False`s. 

Other than that I don't think we should do too many big structural changes just for this.

**Comment by youngmit** [comment]
> @youngmit I don't know. I really like the idea of adding the "did we use this material modification" check in the assembly blueprints:
> 
> https://github.com/terrapower/armi/blob/master/armi/reactor/blueprints/assemblyBlueprint.py#L97-L112
> 
> But I'm not sure if I see how that's possible. Each material would need to actually register a list of 'mat mods' they use for that to work. And they currently don't. Maybe they should?
> 
> Or am I missing something? Right now we just pass the material modifications to the `applyInputParams()` method on a material, and it will use it or not at it's leisure. Is there currently some way to tell what mat mods are used that I'm not seeing?
> 
> Cheers!

You could do this with a custom dict-like container to pass as kwargs to the materials. It could implement a getitem that logs whenever a key is accessed. When all possible materials have beet hit, the blueprint can then check to see if all of the entries have been accessed and raise a warning of not.

**Comment by youngmit** [comment]
BTW @davis8dd has another PR open with #463 now. Someone should probably claim #402 so that we don't step on each others' toes :D

**Comment by john-science** [comment]
I've decided to take a different approach for my solution, I will close this and attempt a different solution soon.

**Pull request closed without merging**
