### PR TITLE
Removing non-existent settings from test files

### LINKED ISSUE #1901: Clean up deprecated setting from `armiRun.yaml`
This is the list I get when I try to run the case:

1. `maxRegionDensityIterations`
2. `eqRingSchedule`
3. `maxFlowZones`
4. `transientForSensitivity`
5. `BOL`
6. `percentNaReduction`
7. `nodeGroup`
8. `economics`
9. `clusterExclusive`
10. `max2SigmaCladIDT`

### PR DESCRIPTION
**Pull request by john-science**
## What is the change?

I removed a bunch of non-existent settings from test files. In turn, this meant tweaking a couple unit tests that referenced such a fake setting.

## Why is the change being made?

Just cleanup, nothing was broken. But I think it will be more clear to people if ARMI didn't see meaningless config settings in our test files.

close #1901

---

## Checklist

- [x] This PR has only [one purpose or idea](https://terrapower.github.io/armi/developer/tooling.html#one-idea-one-pr).
- [x] [Tests](https://terrapower.github.io/armi/developer/tooling.html#test-it) have been added/updated to verify any new/changed code.

- [x] The code style follows [good practices](https://terrapower.github.io/armi/developer/standards_and_practices.html).
- [x] The commit message(s) follow [good practices](https://terrapower.github.io/armi/developer/tooling.html).

- [x] The [release notes](https://terrapower.github.io/armi/developer/tooling.html#add-release-notes) have been updated if necessary.
- [x] The [documentation](https://terrapower.github.io/armi/developer/tooling.html#document-it) is still up-to-date in the `doc` folder.
- [x] The dependencies are still up-to-date in `pyproject.toml`.

### CODE REVIEW

**Comment by john-science** [comment]
@opotowsky I will run a battery of internal tests against this branch, in case somebody is using ARMI test data in their tests. #shrug

**Comment by john-science** [comment]
Oh no.  Some sort of problem installing HD5F on Windows?

Was this what you were seeing?

**Comment by drewj-tp** [comment]
> @opotowsky Oh no. Some sort of problem installing H5PY on Windows?
> 
> Was this what you were seeing?

https://github.com/h5py/h5py/issues/2505

**Review by opotowsky — COMMENTED** [review]
Thanks this is great! It really helps when I need to run a unit test with `-s`.

**Review by opotowsky — APPROVED** [review]

**Pull request merged**
