### PR TITLE
Add Copying Existing Flux Solutions to Cross Section Control Settings

### PR DESCRIPTION
**Pull request by jakehader**
## Description

Adding new functionality to the cross-section settings to copy existing flux solution files during lattice physics evaluations. This is useful for lattice physics codes that allow for an external solver solution file to be provided.

This breaks the crossSectionControl setting for existing applications with the use of pregenerated cross sections. The name of the setting was changed from `fileLocation` to `xsFileLocation` to allow the addition of the `fluxFileLocation` setting.

---

## Checklist

- [x] This PR has only one purpose or idea.
- [x] Tests have been added/updated to verify that the new/changed code works.

- [x] The code style follows [good practices](https://terrapower.github.io/armi/developer/standards_and_practices.html).
- [x] The commit message(s) follow [good practices](https://terrapower.github.io/armi/developer/tooling.html).

- [x] The [release notes](https://terrapower.github.io/armi/release/index.html) (location `doc/release/0.X.rst`) are up-to-date with any bug fixes or new features.
- [x] The documentation is still up-to-date in the `doc` folder.
- [x] The dependencies are still up-to-date in `setup.py`.

### CODE REVIEW

**Comment by mgjarrett** [comment]
I think I like this solution a little more than mine, but we should definitely add a migration from `fileLocation` to `xsFileLocation`, otherwise this is going to be a pesky break in backwards compatibility.

**Review by mgjarrett — APPROVED** [review]

**Comment by jakehader** [comment]
Opened up https://github.com/terrapower/armi/issues/1166 for further clean-ups. Note to @mgjarrett - The `crossSectionControl` setting with `fluxFileLocation` option implies that the name of the file should contain `rzmflx` (case sensitive) for this to function on our end. The issue that is linked will aim to clean up these assumptions more broadly in the code base. There is no settings validation for `rzmflx` in the name because I don't think it's appropriate to mandate this since it should in the future be more general.

**Review by opotowsky — APPROVED** [review]
Approving the added test!

**Comment by mgjarrett** [comment]
The unit tests worked when I ran locally, but they don't seem to be working here. I think the necessary `ISOXA` and `rzmflxYA` files are not being copied into the test directory.

**Comment by opotowsky** [comment]
> The unit tests worked when I ran locally, but they don't seem to be working here. I think the necessary `ISOXA` and `rzmflxYA` files are not being copied into the test directory.

That reminds me -- they also need to be added to the `MANIFEST.in` file. I don't think that solves this problem, though

**Comment by mgjarrett** [comment]
Looks great, nice job!

**Pull request merged**
