### PR TITLE
Removing nearly unused Leaf class

### PR DESCRIPTION
**Pull request by john-science**
## Description

There was [an open ticket](https://github.com/terrapower/armi/issues/1026) to merge `Leaf` into `Component`.  After playing with it, I think the cleaner solution is just to entirely remove the `Leaf` class. Especially since it is ONLY used for `Material`, and we plan on removing the `Material` dependence `ArmiObject` entirely.

This is a map of our current `ArmiObject` structure in ARMI. And I am just taking `Leaf` out of it.

> This is a (-> subclass ->) of that

* `                    Composite -> ArmiObject`
* `Material -> Leaf -> Composite -> ArmiObject`
* `       Component -> Composite -> ArmiObject`
* `           Block -> Composite -> ArmiObject`
* `        Assembly -> Composite -> ArmiObject`

---

## Checklist

- [X] This PR has only one purpose or idea.
- [X] Tests have been added/updated to verify that the new/changed code works.

- [X] The code style follows [good practices](https://terrapower.github.io/armi/developer/standards_and_practices.html).
- [X] The commit message(s) follow [good practices](https://terrapower.github.io/armi/developer/tooling.html).

- [X] The [release notes](https://terrapower.github.io/armi/release/index.html) (location `doc/release/0.X.rst`) are up-to-date with any bug fixes or new features.
- [X] The documentation is still up-to-date in the `doc` folder.
- [X] The dependencies are still up-to-date in `setup.py`.

### CODE REVIEW

**Comment by john-science** [comment]
GitHub seems to be choking on this pretty hard.

It refuses to run the CI with the `main` branch merged in.  So... I'm not sure how to fix that.  I could note the PR and open a new one with a slightly different branch name. I bet that would fix it.

**Comment by opotowsky** [comment]
I don't understand this situation. 😢 

the fails seem to be random?

**Comment by john-science** [comment]
> I don't understand this situation. 😢
> 
> the fails seem to be random?

Well, it _appears_ to be 100% always showing the random error that was fixed in [this PR](https://github.com/terrapower/armi/pull/1044).

But the error message popping up in this PR refers to a file that no longer exists.  So... it's like I merged `main` into this branch and like _half_ the CI jobs here know that, but the other half haven't figured it out yet. And they still have a link to this file that doesn't exist in the main branch.

**Comment by opotowsky** [comment]
> But the error message popping up in this PR refers to a file that no longer exists. So... it's like I merged `main` into this branch and like _half_ the CI jobs here know that, but the other half haven't figured it out yet. And they still have a link to this file that doesn't exist in the main branch.

This must mean the CI isn't running in a clean workspace??? Ah...that's why you want the new PR. Now I get it.

**Comment by john-science** [comment]
Okay, just to be clear, all the unit tests are passing when this PR runs the tests on the [latest commit](https://github.com/terrapower/armi/actions/runs/3744984304/jobs/6358930797).  But for some reason the PR has a stuck work area that still has the [original commit for the PR](https://github.com/terrapower/armi/actions/runs/3744984418/jobs/6358931118), and that is failing.

**Comment by opotowsky** [comment]
I vote to merge!

**Comment by john-science** [comment]
> I vote to merge!

Naw.  Let's not yet.

Give me a few.

**Comment by opotowsky** [comment]
I rescind my vote!

**Pull request merged**
