### PR TITLE
Fix building of MacroXS tables when MPI import fails #357

### PR DESCRIPTION
**Pull request by keckler**
When mpi4py import fails, `MPI_SIZE` defaults to 1. Use this to disable the
execution of MPI commands. See #357

### CODE REVIEW

**Comment by keckler** [comment]
Eh, wait, I've got a failing test.

**Comment by theJollySin** [comment]
The code coverage just went down because you added lines to the code.  So... by definition the % code coverage went down very slightly for the whole project.  Oh well.  (It would be nice if we could tell it not to fail code coverage unless it dropped by more than 0.01% or something.)

**Fun Fact**: The file `macroXSGenerationInterface.py` has exactly 0% code coverage.

**Comment by keckler** [comment]
Yeah, I saw that. What I meant when I said a test failed was that the check-formatting test failed cause I had code lines longer than 80 characters. So I fixed that and push it back up. It should be ready now.

**Comment by jakehader** [comment]
This was tested manually on a machine that did not have MSMPI and it worked. I will accept and merge in.

**Review by jakehader — APPROVED** [review]

**Pull request merged**
