### PR TITLE
Add unit test coverage for blocks.py

### PR DESCRIPTION
**Pull request by albeanth**
## What is the change?
While working on PR #1425, I found this little section of blocks.py that had no test coverage. This PR adds test coverage.
https://github.com/terrapower/armi/blob/d341941e570dc731a4b0ab9017acc65c35d43098/armi/reactor/blocks.py#L762-L767

## Why is the change being made?
Unit test coverage good. 

---

## Checklist

- [x] This PR has only one purpose or idea.
- [x] Tests have been added/updated to verify that the new/changed code works.

- [x] The code style follows [good practices](https://terrapower.github.io/armi/developer/standards_and_practices.html).
- [x] The commit message(s) follow [good practices](https://terrapower.github.io/armi/developer/tooling.html).

- ~The [release notes](https://terrapower.github.io/armi/release/index.html) (location `doc/release/0.X.rst`) are up-to-date with any important changes.~ Not needed.
- [x] The documentation is still up-to-date in the `doc` folder.
- [x] The dependencies are still up-to-date in `pyproject.toml`.

### CODE REVIEW

**Comment by albeanth** [comment]
> The coverage dropped quite a bit with this PR. That's... odd, right?

Uhh yeah, that's really odd. Especially since the coverage report is showing a big 'ol drop for totally unrelated files....? Any idea what's going on here?
image

**Comment by albeanth** [comment]
And to make it more odd, the one little section of code I added a test for had coverage go up. 

Maybe there was a glitch of some sort? Unplug it and plug it back in?

**Comment by opotowsky** [comment]
The issue is that there was a `coverage` update released four days ago that has fixed a bug with some of the `excluded_lines` (found in `.coveragerc`) not being honored. So now the "relevant lines" has gone down but so have some of the "covered lines"

Changelog for coverage 7.3.2: https://coverage.readthedocs.io/en/7.3.2/changes.html#version-7-3-2-2023-10-02

The first bullet looked like the only one that would impact cov calcs. Here's the github issue: https://github.com/nedbat/coveragepy/issues/1684

Without even looking at the fix to the issue, I see this:
MicrosoftTeams-image (25)


Left is main (coverage v7.3.1) and right is this PR (coverage v7.3.2). This is just a random file with a cov drop among many.

In the relevant lines, there's 202 fewer being counted. In the covered lines, 199 fewer. I couldn't find the 3 "newly uncovered" lines in the file, but this little shake-up is certainly the cause of the coverage drop we are seeing among all the newer PRs.

**Comment by john-science** [comment]
Well, that's a great find, Arrielle.

So, we have options:

1. We can ignore the coverage report for just this PR.
2. We can pin the coverage version in ARMI CI.
3. We can merge some simple docstring PR into `main`, and then merge `main` into this PR.

**Comment by albeanth** [comment]
My vote is either 1 or 3. Up to you two though!

**Comment by opotowsky** [comment]
I also vote 1 or 3!

**Comment by albeanth** [comment]
I think #1430 could be our PR to reset the coverage reporting.

**Comment by john-science** [comment]
@albeanth If you merge `main` into your branch, the build will pass again.

**Review by john-science — APPROVED** [review]

**Review by john-science — APPROVED** [review]

**Pull request merged**
