### PR TITLE
Changing constant params to Volume Integrated

### PR DESCRIPTION
**Pull request by mgjarrett**
## What is the change?

Reactivity coefficient parameters for the Doppler constant were configured with the `ParamLocation.AVERAGE` location attribute. These parameters are actually `ParamLocation.VOLUME_INTEGRATED`, so they are being changed.

## Why is the change being made?

The Doppler constant for a given block is proportional to the size of the block. If two blocks were to be combined into one, the combined block Doppler constant would be the sum of the two smaller blocks:
```python
b.p.rxFuelDopplerConstant = b1.p.rxFuelDopplerConstant + b2.p.rxFuelDopplerConstant
````

This is achieved with `ParamLocation.VOLUME_INTEGRATED`, not `PararmLocation.AVERAGE`.

The Doppler constant is directly related to the Doppler coefficient in units of pcm/K; the coefficients were already labeled as `ParamLocation.VOLUME_INTEGRATED`.

---

## Checklist

- [x] This PR has only [one purpose or idea](https://terrapower.github.io/armi/developer/tooling.html#one-idea-one-pr).
- [ ] [Tests](https://terrapower.github.io/armi/developer/tooling.html#test-it) have been added/updated to verify any new/changed code.

- [x] The code style follows [good practices](https://terrapower.github.io/armi/developer/standards_and_practices.html).
- [x] The commit message(s) follow [good practices](https://terrapower.github.io/armi/developer/tooling.html).

- [x] The [release notes](https://terrapower.github.io/armi/developer/tooling.html#add-release-notes) have been updated if necessary.
- [x] The [documentation](https://terrapower.github.io/armi/developer/tooling.html#document-it) is still up-to-date in the `doc` folder.
- [x] The dependencies are still up-to-date in `pyproject.toml`.

### CODE REVIEW

**Comment by john-science** [comment]
What's the status of this PR?

Nominally, it looks like you did what you wanted.  Are you waiting to add a unit test or something?

**Review by albeanth — APPROVED** [review]
On testing: these params are totally unused in ARMI and fall under the "incomplete feature" umbrella imo (i.e., changing them has no affect in ARMI and it doesn't make sense to test them here). 

I think they should be pulled internal where they are actually used.

**Comment by john-science** [comment]
@mgjarrett Can you put a small release note under the [API Changes](https://github.com/terrapower/armi/blob/f9903fe5a5d30ceda389d6494020f7a0c0f01b92/doc/release/0.3.rst?plain=1#L16) section?  Thanks!

**Comment by john-science** [comment]
It's odd this change doesn't require any unit tests changes, right?

**Review by john-science — APPROVED** [review]
Great!

**Pull request merged**
