### PR TITLE
Adding a 'good PR' guide to the Docs

### PR DESCRIPTION
**Pull request by john-science**
## Description

Adding a guide for a "good PR" to the docs. And unifying this guide with the GitHub "pull_request_template.md".

---

## Checklist                                                                                                                                                                                                       
                                                                                                                                                                                                                   
<!--                                                                                                                                                                                                               
    Put an `x` in the boxes you have completed so far. You can check a box after creating the PR.                                                                                                                  
    If you're unsure about any of them, don't hesitate to ask. We're here to help!                                                                                                                                 
    Learn what a "good PR" looks like here: https://terrapower.github.io/armi/developer/tooling.html#good-pull-requests                                                                                            
-->                                                                                                                                                                                                                
                                                                                                                                                                                                                   
- [x] This PR has only one purpose or idea.                                                                                                                                                                        
- [x] Tests have been added/updated to verify that the new/changed code works.                                                                                                                                     
                                                                                                                                                                                                                   
<!-- Check the code quality -->                                                                                                                                                                                    
                                                                                                                                                                                                                   
- [x] The code style follows [good practices](https://terrapower.github.io/armi/developer/standards_and_practices.html).                                                                                           
- [x] The commit message(s) follow [good practices](https://terrapower.github.io/armi/developer/tooling.html).                                                                                                     
                                                                                                                                                                                                                   
<!-- Check the project-level cruft -->                                                                                                                                                                             
                                                                                                                                                                                                                   
- [x] The [release notes](https://terrapower.github.io/armi/release/index.html) are up-to-date with any bug fixes or new features.                                                                                 
- [x] The documentation is still up-to-date in the `doc` folder.                                                                                                                                                   
- [x] The dependencies are still up-to-date in `setup.py`.

### CODE REVIEW

**Comment by john-science** [comment]
I have assigned more reviewers than usual to this PR, because I think this PR is more opinion/discussion based than usual.

**Review by keckler — APPROVED** [review]
I like the new checkboxes a lot more than what was there before!

**Review by opotowsky — APPROVED** [review]
You know, I was never quite certain if I should be checking the boxes or letting the reviewer check the boxes. I like the new boxes, but could you add instruction on that? Not a merge-blocking request, so approved. 

Great updates!

**Review by opotowsky — APPROVED** [review]
<3

Thanks for that!

**Review by jakehader — APPROVED** [review]

**Pull request merged**
