### PR TITLE
Nhflux variant bug

### PR DESCRIPTION
**Pull request by Nebbychadnezzar**
## Description

This pull request fixes issue [680](https://github.com/terrapower/armi/issues/680). Achieving complete reading of the VARIANT NHFLUX file is not intended by this pull request.

---

## Checklist

- [x] The code is understandable and maintainable to people beyond the author.
- [x] Tests have been added/updated to verify that the new or changed code works.
- [x] There is no commented out code in this PR.
- [x] The commit message follows [good practices](https://terrapower.github.io/armi/developer/tooling.html).
- [x] All docstrings are still up-to-date with these changes.

If user exposed functionality was added/changed:

- [x] Documentation added/updated in the `doc` folder.
- [x] New or updated dependencies have been added to `setup.py`.

### CODE REVIEW

**Comment by Nebbychadnezzar** [comment]
I know there aren't added tests here yet. I'd like some input on that before I start writing a test.

I have tested this updated code on a representation model using both Nodal and VARIANT (P1/P1 and P3/P3 transport options), though.

**Comment by john-science** [comment]
> I know there aren't added tests here yet. I'd like some input on that before I start writing a test.

In the _ideal_ scenario, when you fix a bug you add a unit test that used to fail, but doesn't any more.

If that scenario requires just TOO MUCH input data to run, it would be nice to have unit tests that test each little/tiny method you changed to show that they do what you want them to do now.

As always, feel free to contact me about testing.

**Comment by Nebbychadnezzar** [comment]
Testing?! What's that?

I wanted some input before I started writing tests, since this at first appeared to be a bit of an odd update. However, after looking a bit through the `test_nhflux.py` file, I think I can whip something up that would be serviceable. Hang tight while I do that and add some commits.

**Review by ntouran — APPROVED** [review]
Looks good to me. Would it be possible to add a small dummy `NHFLUX_VARIANT` file that we could use in a new unit test to ensure this works as expected? I think the `NHFLUX_VARIANT` file format must be changing a big vs. version because we've *definitely* used this NHFLUX data with variant in the past.

**Comment by Nebbychadnezzar** [comment]
Sounds good, @ntouran. I will include this information in the tests.

**Comment by Nebbychadnezzar** [comment]
A new test class has been added in`test_nhflux` to cover at least some of the aspects of the new code that's been added. Adding something that has nMoms > 0 would require executing P3 with anisotropic cross sections, which is not currently part of the test case used with `test_nhflux`. Running something with iwnhfl == 1 would require running VARPOW, which in turn would require running a coupled n/g job.

**Review by john-science — APPROVED** [review]

**Pull request merged**
