### PR TITLE
Creating a one-block test reactor to speed up testing

### LINKED ISSUE #1736: Create a super minimal test reactor, and use it to speed up our unit tests
Right now, ARMI provides the test functionality to generate a test reactor object with [`loadTestReactor()`](https://github.com/terrapower/armi/blob/8ab9099a49d4731da207f5e844f60ea6ebefddcd/armi/reactor/tests/test_reactors.py#L140). By default that uses [`armiRun.yaml`](https://github.com/terrapower/armi/blob/8ab9099a49d4731da207f5e844f60ea6ebefddcd/armi/tests/armiRun.yaml), which generates a hex-assembly-based reactor with 9 rings and 73 assemblies.

If the developer wants a smaller reactor, they can use the method [`reduceTestReactorRings()`](https://github.com/terrapower/armi/blob/8ab9099a49d4731da207f5e844f60ea6ebefddcd/armi/reactor/tests/test_reactors.py#L204) to reduce the number of rings in the test reactor. But that is itself quite slow, and _can_ slow down a test.

> The only silver-bullet solution to speeding up our unit tests would be to generate a smaller test reactor from the start.

I propose the solution:

1. We create a `loadTestReactorOneBlock()`, which generates a 1-assembly, 1-block reactor using the existing [`refOneBlockReactor.yaml`](https://github.com/terrapower/armi/blob/8ab9099a49d4731da207f5e844f60ea6ebefddcd/armi/tests/refOneBlockReactor.yaml).
2. Then, where possible, we replace `loadTestReactor()` with the new function to speed up our unit tests.

### PR DESCRIPTION
**Pull request by john-science**
## What is the change?

In this PR I created a test reactor from an existing single test block reactor:

`armi/tests/smallestTestReactor/armiRunSmallest.yaml`

> Using this new test reactor in dozens of tests, sped up our unit tests by 25-30%!

## Why is the change being made?

I am just trying to speed up our unit tests. (Close #1736)

On my personal laptop, I saw _many_ unit tests go from between 2 or 6 seconds down to 0.1 to 0.2 seconds.

Perhaps more importantly, we now have the tooling to use across the ecosystem.

**NOTE**: Not all unit tests can use such a small reactor. Be design, if you are doing something like shuffling multiple assemblies, you can not use the smaller test reactor.

---

## Checklist

- [X] This PR has only [one purpose or idea](https://terrapower.github.io/armi/developer/tooling.html#one-idea-one-pr).
- [X] [Tests](https://terrapower.github.io/armi/developer/tooling.html#test-it) have been added/updated to verify any new/changed code.

- [X] The code style follows [good practices](https://terrapower.github.io/armi/developer/standards_and_practices.html).
- [X] The commit message(s) follow [good practices](https://terrapower.github.io/armi/developer/tooling.html).

- [X] The [release notes](https://terrapower.github.io/armi/developer/tooling.html#add-release-notes) have been updated if necessary.
- [X] The [documentation](https://terrapower.github.io/armi/developer/tooling.html#document-it) is still up-to-date in the `doc` folder.
- [X] The dependencies are still up-to-date in `pyproject.toml`.

### CODE REVIEW

**Comment by john-science** [comment]
Well, unsuprisingly...

> It works on my computer.

I'll fix it.

**Comment by john-science** [comment]
This PR reduces SOME tests run time by 98%, but it only reduces the overall runtime of ALL the ARMI tests together by 25-30%.

Still, that's something. And now we have the tooling to us across the ecosystem.

**Comment by john-science** [comment]
@opotowsky I reduced the scope of this PR for you.

I moved the `runLog.py` fix and the Python 3.7 thing to another PR, which Tony got.

Hope that helps!

**Review by opotowsky — APPROVED** [review]
This is amazing! can't wait to use it downstream too!

**Pull request merged**
