### PR TITLE
Version bumping ARMI to 0.2.8

### PR DESCRIPTION
**Pull request by john-science**
## What is the change?

1. Version bumping ARMI to 0.2.8
2. Cleaning up the `ruff.toml`

## Why is the change being made?

1. ARMI is at a stable API point, after a very active period.
2. The `ruff.toml` is new, and while trying to clean it up I found I had added TONS of unnecessary `# noqa: ` comments in our code. Less is more!

---

## Checklist

- [ ] This PR has only one purpose or idea.
- [ ] Tests have been added/updated to verify that the new/changed code works.

- [X] The code style follows [good practices](https://terrapower.github.io/armi/developer/standards_and_practices.html).
- [X] The commit message(s) follow [good practices](https://terrapower.github.io/armi/developer/tooling.html).

- [X] The [release notes](https://terrapower.github.io/armi/release/index.html) (location `doc/release/0.X.rst`) are up-to-date with any important changes.
- [X] The documentation is still up-to-date in the `doc` folder.
- [X] The dependencies are still up-to-date in `setup.py`.

### CODE REVIEW

**Comment by john-science** [comment]
The code coverage diff here is an idiot.  Not a valid diff.

**Review by opotowsky — APPROVED** [review]
Looks good to me. Thanks!!

**Comment by john-science** [comment]
@opotowsky I assume this is getting pushed off a week?

**Comment by opotowsky** [comment]
We should be ready to merge this by tomorrow afternoon 🤞

**Pull request merged**
