### PR TITLE
Use b.core instead of b.r.core.

### PR DESCRIPTION
**Pull request by mgjarrett**
## Description

Blocks have an `r` property and a core property. Both functions just look up the chain of ancestors of the block to find the `core` and `reactor`. It's unnecessary to go all the way up to the `reactor` just to then grab the `core` off of it.

---

## Checklist

- [x] This PR has only one purpose or idea.
- [x] Tests have been added/updated to verify that the new/changed code works.

- [x] The code style follows [good practices](https://terrapower.github.io/armi/developer/standards_and_practices.html).
- [x] The commit message(s) follow [good practices](https://terrapower.github.io/armi/developer/tooling.html).

- [x] The [release notes](https://terrapower.github.io/armi/release/index.html) (location `doc/release/0.X.rst`) are up-to-date with any bug fixes or new features.
- [x] The documentation is still up-to-date in the `doc` folder.
- [x] The dependencies are still up-to-date in `setup.py`.

### CODE REVIEW

**Comment by mgjarrett** [comment]
Basically acting on the note in this docstring:

https://github.com/terrapower/armi/blob/646f23da6ce77fb410dffd202dbddb0fba57da63/armi/reactor/blocks.py#L173-L181

Can't completely remove `b.r` yet because it's used to get active nuclides from reactor blueprints here:

https://github.com/terrapower/armi/blob/646f23da6ce77fb410dffd202dbddb0fba57da63/armi/reactor/blocks.py#L737

**Comment by john-science** [comment]
I love it!

Can we remove the comment you link on line ~173 now?

**Comment by mgjarrett** [comment]
> Can we remove the comment you link on line ~173 now?

I would like to remove that entire function, but we still have one case of `b.r.blueprints` so we can't remove this property altogether. I think we can trim some of the docstring and make it better. I'll push a commit with a new docstring.

**Review by keckler — APPROVED** [review]
I think these are good changes.

With regards to your comment:
> Can't completely remove b.r yet because it's used to get active nuclides from reactor blueprints here:

Is there a reason why we want to remove `b.r` completely? I agree that, in the cases you changed `b.r.core` -> `b.core`, it makes sense because it avoids unnecessary computation. But I think that `b.r` could still be useful in the API.

Plus, if we're trying to avoid changes to the API, I would view that as an unnecessary change to the API.

Just a thought.

**Comment by mgjarrett** [comment]
I agree that removing `b.r` would be an unnecessary change to the API. The docstring had this comment:

```
It may make sense to try to factor out the usage of ``b.r``
```

So that's why I thought it might be desirable to remove it. But as long as it's being used, and it's not hurting anything, it makes more sense to leave it in for continuity.

**Review by john-science — APPROVED** [review]

**Pull request merged**
