### PR TITLE
Speed up runLog

### PR DESCRIPTION
**Pull request by opotowsky**
## Description

(trying to avoid tagging stilley for reviews if possible)

A profile of a long case run showed that **4.5 hours** was being spent inside `runLog`, and digging further in, specifically evaluating `os.path.exists`. 

~This proposed change cut that time down to 2.3 hours (just not running `os.path.exists` if the log level isn't applicable)~ Chris' suggestion that `os.path.exists` can be module level has the time spent in `runLog` down to **9 minutes**.

~However, I'd like to consider other options on how this speedup can happen. Would moving it to `__init__` be possible? Or is running it only one time problematic? There are some places where this gets evaluated thousands of times in a loop.~

Update: This was evaluated using a pretty hefty run that included tight coupling. The time spent in `runLog` without tight coupling enabled was never all that bad / didn't see much improvement. But yay for the tight coupling cases!

---

## Checklist

- [x] This PR has only one purpose or idea.
- [ ] Tests have been added/updated to verify that the new/changed code works.

- [x] The code style follows [good practices](https://terrapower.github.io/armi/developer/standards_and_practices.html).
- [x] The commit message(s) follow [good practices](https://terrapower.github.io/armi/developer/tooling.html).

- [x] The [release notes](https://terrapower.github.io/armi/release/index.html) (location `doc/release/0.X.rst`) are up-to-date with any bug fixes or new features.
- [x] The documentation is still up-to-date in the `doc` folder.
- [x] The dependencies are still up-to-date in `setup.py`.

### CODE REVIEW

**Comment by john-science** [comment]
That's awesome!

It would also help to speed up `runLog` if we weren't logging a million useless things every time node.  Everyone seems convinced while they are working on a PR that their new log line needs to be info, not debug. Because it was really interesting to them that day. But they never look at the log line again. 99.9% of the stuff we log at info level is read less than once a year and should be moved to debug.

**Comment by keckler** [comment]
I would agree that, just by looking at the code, it appears the logDir could be created during the `__init__()`.

I even think it could go up higher somewhere? So when `createLogDir()` is called in this instance, it always passes in `LOG_DIR`:
https://github.com/terrapower/armi/blob/8d3c64ff5899f40a03c3ac56ba6412c552eb4a34/armi/runLog.py#L526-L529

But `LOG_DIR` is a _module_ variable:
https://github.com/terrapower/armi/blob/8d3c64ff5899f40a03c3ac56ba6412c552eb4a34/armi/runLog.py#L67-L71

If `LOG_DIR` never changes during the run, which it doesn't, then the call to `createLogDir(LOG_DIR)` will always produce the same result. So I think it should be safe just to call `createLogDir(LOG_DIR)` from the module level and hold that as a module object, right?

I don't know... I think what I said is correct, but then it makes it seem odd that one is able to supply a `logDir` parameter to `createLogDir()` in the first place, because I don't see that ability being exercised anywhere...

**Comment by opotowsky** [comment]
Thanks for looking into it, @keckler. I agree. The only issue is if someone deletes the log dir during the run, which would just be weird and not a situation I think we should bother coding for. Just wondering if there's some other situation I'm not seeing that would require this to be done at this stage. I'm going to put it at the module level and run another (much shorter) profile comparison.

**Comment by opotowsky** [comment]
Ok, @keckler and @albeanth ....took awhile to get the testing done right because I learned the hard way this isn't a problem for non-tight coupling cases. (Plus, all kinds of other  slowdowns that need not be mentioned). Updated the PR description and I'm ready for review!

@monufer tl;dr runLog on tight coupling cases is 4.5 hrs --> 9 minutes. Great catch!

**Review by keckler — APPROVED** [review]
Such a tiny change for such a big impact.

Thanks for discovering this!

**Review by albeanth — APPROVED** [review]

**Pull request merged**
