### PR TITLE
Replace ppt generated illustrations for graphviz

### PR DESCRIPTION
**Pull request by albeanth**
## Description
In the documentation additions in #1033, the loose and tight coupling illustrations had Powerpoint generated illustrations as placeholders. This PR replaces those pngs with graphviz generated illustrations that are hopefully clearer and more maintainable. 

https://github.com/terrapower/armi/pull/1033#discussion_r1072414032

---

## Checklist

- [x] This PR has only one purpose or idea.
- [ ] ~Tests have been added/updated to verify that the new/changed code works.~
    - Just documentation, no tests to be added.  

- [x] The code style follows [good practices](https://terrapower.github.io/armi/developer/standards_and_practices.html).
- [x] The commit message(s) follow [good practices](https://terrapower.github.io/armi/developer/tooling.html).

- [ ] ~The [release notes](https://terrapower.github.io/armi/release/index.html) (location `doc/release/0.X.rst`) are up-to-date with any bug fixes or new features.~
    - Not changing text in documentation, just images. 
- [x] The documentation is still up-to-date in the `doc` folder.
- [x] The dependencies are still up-to-date in `setup.py`.

### CODE REVIEW

**Comment by albeanth** [comment]
Here's what the new images look like when the docs are built. 
image

**Review by opotowsky — APPROVED** [review]
nice!

**Comment by john-science** [comment]
I love it!  @albeanth 

Are you SURE we don't need to add any dependencies to the repo to make this work?

If so, GREAT, I'm thrilled.

**Review by john-science — APPROVED** [review]

**Comment by albeanth** [comment]
> I love it! @albeanth
> 
> Are you SURE we don't need to add any dependencies to the repo to make this work?
> 
> If so, GREAT, I'm thrilled.

Yep! No additional dependencies. 

The _one_ thing that came up when I was making this. I didn't see any reference in the docs about having to run https://github.com/terrapower/armi/blob/main/doc/requirements-docs.txt. If that is not run, then the docs _do_ build locally, but they're all messed up.

**Pull request merged**
