### PR TITLE
Fix snapshot

### PR DESCRIPTION
**Pull request by onufer**
## What is the change?

Finalize database changes for snapshots

## Why is the change being made?

#1090 was merged prior to final internal testing. after internal testing some minor changes were needed to snapshots.

---

## Checklist

- [x] This PR has only [one purpose or idea](https://terrapower.github.io/armi/developer/tooling.html#one-idea-one-pr).
- [ ] [Tests](https://terrapower.github.io/armi/developer/tooling.html#test-it) have been added/updated to verify any new/changed code.

- [x] The code style follows [good practices](https://terrapower.github.io/armi/developer/standards_and_practices.html).
- [x] The commit message(s) follow [good practices](https://terrapower.github.io/armi/developer/tooling.html).

- [x] The [release notes](https://terrapower.github.io/armi/developer/tooling.html#add-release-notes) have been updated if necessary.
- [x] The [documentation](https://terrapower.github.io/armi/developer/tooling.html#document-it) is still up-to-date in the `doc` folder.
- [x] The dependencies are still up-to-date in `pyproject.toml`.

### CODE REVIEW

**Review by keckler — COMMENTED** [review]
I think this looks good. But because the logic is a little bit deep, it would be ideal if a test could be added to make sure that the writing and closing sequence is being performed correctly during snapshots.

Would this be possible?

**Review by opotowsky — COMMENTED** [review]
Can you change this line

https://github.com/terrapower/armi/blob/f04b36527adb3102e5d2ceeadcf8af7a256fde3e/armi/bookkeeping/db/database3.py#L122

to `timeNodeGroupPattern = re.compile(r"^c(\d\d)n(\d\d).*$")`?

That will allow compareDB to find statepoints that match `cXXYYEOL`

**Comment by keckler** [comment]
After offline discussion, I understand that we have an internal integration test that covers this scenario. I am okay without the addition of another unit test to this PR.

Right now the unit tests are failing. I can approve when that is resolved.

**Comment by john-science** [comment]
The unit tests are currently broke.

And `ruff` requests some changes.

**Review by keckler — APPROVED** [review]

**Review by keckler — APPROVED** [review]

**Review by john-science — APPROVED** [review]

**Pull request merged**
